"""empty message

Revision ID: c090a872e0dd
Revises: 61b6cbda80b0
Create Date: 2020-12-15 08:48:16.442942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c090a872e0dd'
down_revision = '61b6cbda80b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.String(length=50), server_default='0'))
    op.create_unique_constraint(None, 'projects', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
