"""empty message

Revision ID: d51f14be703a
Revises: 920056066b24
Create Date: 2020-11-30 12:45:32.125979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51f14be703a'
down_revision = '920056066b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_project_tag', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('post_project_tag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_project_tag', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_project_tag', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_project_tag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('post_project_tag', 'id')
    # ### end Alembic commands ###
