"""empty message

Revision ID: e9ea27776c8e
Revises: d51f14be703a
Create Date: 2020-11-30 13:06:14.451693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ea27776c8e'
down_revision = 'd51f14be703a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_project_tag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_project_tag', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_project_tag', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_project_tag', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
